// native/android/JarvisAccessibilityPackage.kt
// Registers JarvisAccessibilityModule with React Native's bridge.
// Goes in the same folder as the other .kt files:
// android/app/src/main/java/com/yourapp/jarvis/

package com.cyber.jarvis

import com.facebook.react.ReactPackage
import com.facebook.react.bridge.NativeModule
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.uimanager.ViewManager

class JarvisAccessibilityPackage : ReactPackage {
    override fun createNativeModules(reactContext: ReactApplicationContext): List<NativeModule> {
        return listOf(JarvisAccessibilityModule(reactContext))
    }

    override fun createViewManagers(reactContext: ReactApplicationContext): List<ViewManager<*, *>> {
        return emptyList()
    }
}

/*
Then register it in MainApplication.kt (generated by `expo prebuild`), inside
the getPackages() override, e.g.:

override fun getPackages(): List<ReactPackage> {
    val packages = PackageList(this).packages
    packages.add(JarvisAccessibilityPackage())
    return packages
}
*/
